// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package csharpjava;

@net.sf.jni4net.attributes.ClrType
public class CSharpClass extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected CSharpClass(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public CSharpClass() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        csharpjava.CSharpClass.__ctorCSharpClass0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorCSharpClass0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Z")
    public native static boolean print(java.lang.String message);
    
    @net.sf.jni4net.attributes.ClrMethod("(II)I")
    public native static int add(int a, int b);
    
    public static system.Type typeof() {
        return csharpjava.CSharpClass.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        csharpjava.CSharpClass.staticType = staticType;
    }
    //</generated-proxy>
}
